# General settings
seed: 8888
device: "cuda:5"  # Change to the GPU you want to use
debug: True  # For logging DEBUG level messages otherwise INFO

# Directories
data_dir: "/home/sanoojan/Video_diffusion/AnyV2V"
model_name: "i2vgen-xl"
task_name: "Prompt-Based-Editing"
Experiment_name: "DBG_guidance_9_500_same_img"
video_name: "Clip+-1Jouc19Ixo+P0+C1+F4196-4320"
output_dir: "${data_dir}/Results_DATA/${Experiment_name}/${task_name}/${model_name}/${video_name}"

# Data
image_size: [512, 512]
video_dir: "${data_dir}/data/Data/VFHQ-Test/GT/Interval1_512x512_LANCZOS4"
video_frames_path: "${video_dir}/${video_name}"
# edited_first_frame_path: "${data_dir}/Edited_frames/REFace/${video_name}/00000000.png"
edited_first_frame_path: "${video_frames_path}/00000000.png"
edited_frames_path: "${data_dir}/Edited_frames/REFace/${video_name}"
ddim_latents_path: "${data_dir}/inversions_DATA/${Experiment_name}/${model_name}/${video_name}/ddim_latents"
null_latents_path: "${data_dir}/inversions_DATA/${Experiment_name}/${model_name}/${video_name}/null_latents"
naming_scheme: 8
edited_scheme: 8

# Video processing
n_frames: 16
target_fps: 8

# DDIM inversion
inverse_config:
  force_inversion: True
  cfg: 1.0
  n_steps: 500   # change this to 500
  prompt: "A human"
  negative_prompt: ""
  output_dir: "${ddim_latents_path}"
  image_size: "${image_size}"
  n_frames: "${n_frames}"
  target_fps: "${target_fps}" 

#null_optimization
null_optimization:
  null_optimization: False
  num_inner_steps: 1
  epsilon: 1e-5
  n_steps: 50 # change this to 500
  guidance_scale: 9.0
  image_size: "${image_size}"
  n_frames: "${n_frames}"
  output_dir: "${null_latents_path}"

# DDIM reconstruction
recon_config:
  enable_recon: False
  cfg: 9.0
  n_steps: 500
  ddim_init_latents_t_idx: 3
  negative_prompt: "Distorted, discontinuous, Ugly, blurry, low resolution, motionless, static, disfigured, disconnected limbs, Ugly faces, incomplete arms"
  prompt: "a human"
  image_size: "${image_size}"
  n_frames: "${n_frames}"
  target_fps: "${target_fps}"

# Editing settings
editing:
  n_edited_frames: 1
  cfg: 9.0
  n_steps: 50
  editing_prompt: "a man doing exercises for the body and mind"
  editing_negative_prompt: "Distorted, discontinuous, Ugly, blurry, low resolution, motionless, static, disfigured, disconnected limbs, Ugly faces, incomplete arms"
  ddim_init_latents_t_idx: 0
  random_ratio: 0.0
  ddim_inv_prompt: ""
  
# PnP configuration
pnp:
  pnp_f_t: 1.0
  pnp_spatial_attn_t: 1.0
  pnp_temp_attn_t: 1.0
  n_steps: 50