# General settings
seed: 8888
device: "cuda:4"  # Change to the GPU you want to use
debug: False  # For logging DEBUG level messages otherwise INFO

# Directories
data_dir: "/home/sanoojan/Video_diffusion/AnyV2V"
model_name: "i2vgen-xl"
task_name: "Prompt-Based-Editing"
Experiment_name: "Debug"
video_name: "An Old Man Doing Exercises For The Body And Mind"
output_dir: "${data_dir}/Results/${Experiment_name}/${task_name}/${model_name}/${video_name}"

# Data
image_size: [512, 512]
video_dir: "${data_dir}/demo"
video_frames_path: "${video_dir}/${video_name}"
edited_first_frame_path: "${data_dir}/demo/${video_name}/edited_first_frame/yann_lecunn.png"
edited_frames_path: "${data_dir}/demo/${video_name}/edited_first_frame/Yann"
ddim_latents_path: "${data_dir}/inversions_ind/${Experiment_name}/${model_name}/${video_name}/ddim_latents"

# Video processing
n_frames: 4
target_fps: 8

# DDIM inversion
inverse_config:
  force_inversion: True
  cfg: 1.0
  n_steps: 5   # change this to 500
  prompt: "A human"
  negative_prompt: ""
  output_dir: "${ddim_latents_path}"
  image_size: "${image_size}"
  n_frames: "${n_frames}"
  target_fps: "${target_fps}" 

#null_optimization
null_optimization:
  null_optimization: True
  num_inner_steps: 1
  epsilon: 9.0
  n_steps: 5
  guidance_scale: 9.0
  image_size: "${image_size}"
  n_frames: "${n_frames}"

# DDIM reconstruction
recon_config:
  enable_recon: False
  cfg: 9.0
  n_steps: 50
  ddim_init_latents_t_idx: 3
  negative_prompt: "Distorted, discontinuous, Ugly, blurry, low resolution, motionless, static, disfigured, disconnected limbs, Ugly faces, incomplete arms"
  prompt: "a human"
  image_size: "${image_size}"
  n_frames: "${n_frames}"
  target_fps: "${target_fps}"

# Editing settings
editing:
  n_edited_frames: 1
  cfg: 9.0
  n_steps: 50
  editing_prompt: "a man doing exercises for the body and mind"
  editing_negative_prompt: "Distorted, discontinuous, Ugly, blurry, low resolution, motionless, static, disfigured, disconnected limbs, Ugly faces, incomplete arms"
  ddim_init_latents_t_idx: 0
  random_ratio: 0.0
  ddim_inv_prompt: ""
  
# PnP configuration
pnp:
  pnp_f_t: 1.0
  pnp_spatial_attn_t: 1.0
  pnp_temp_attn_t: 1.0
  n_steps: 50